chore: update Subscription container docs
Shopify/argo-admin-template pull request #80
Opened 2020-10-23 17:41 UTC by henrytao-me

Ref https://github.com/Shopify/app-extension-libs/issues/1087

2020-10-23 17:52 UTC, vividviolet requested changes

2020-10-23 17:52 UTC, vividviolet commented on docs/ExtensionPoints/ProductSubscription/README.md
>        done();
Same comment as the other PR, the description for `done` needs to say that the container will be closed automatically

2020-10-26 14:12 UTC, vividviolet requested changes
@henrytao-me we need to make changes the Simulator host to call close on `done`

2020-10-26 14:21 UTC, henrytao-me commented
Good catch.

2020-10-26 14:28 UTC, henrytao-me commented
🎩-ed locally with https://github.com/Shopify/argo-admin-cli/pull/36. The AppOverlay and Modal are closed properly after calling `done`

2020-10-26 15:40 UTC, henrytao-me commented
🎩-ed again after argo-admin-cli releases 0.1.11. LGTM

2020-10-26 18:01 UTC, vividviolet approved these changes

2020-10-26 18:02 UTC, merged